# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosHermanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=50)),
                ('estudios', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('tecnico', 'Tecnico'), ('lic', 'Lic'), ('posgrado ', 'Posgrado'), ('sinestudio', 'Sin estudio')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPsicofisiologicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mop_hinchados', models.CharField(choices=[('1', 'Muy frecuente'), ('2', 'Frecuente'), ('3', 'A veces'), ('4', 'Antes'), ('5', 'Nunca')], default='Nunca', max_length=50)),
                ('dolores_vientre', models.CharField(choices=[('1', 'Muy frecuente'), ('2', 'Frecuente'), ('3', 'A veces'), ('4', 'Antes'), ('5', 'Nunca')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormatoEntrevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('carrera', models.CharField(max_length=50)),
                ('codigo_postal', models.IntegerField()),
                ('tipo_vivienda', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento')], default='casa', max_length=50)),
                ('estadovivienda', models.CharField(choices=[('propia', 'Propia'), ('rentada', 'Rentada'), ('prestada', 'Prestada'), ('otro', 'Otro')], default='propia', max_length=100)),
                ('especificacion_vivienda', models.CharField(default='', max_length=50)),
                ('personas_vives', models.IntegerField()),
                ('nom_padre', models.CharField(max_length=50)),
                ('edad_padre', models.IntegerField()),
                ('padre_trabaja', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='si', max_length=50)),
                ('padre_profesion', models.CharField(max_length=50)),
                ('padre_tipo_trabajo', models.CharField(max_length=50)),
                ('padre_domicilio', models.CharField(max_length=50)),
                ('padre_telefono', models.IntegerField()),
                ('nom_madre', models.CharField(max_length=50)),
                ('edad_madre', models.IntegerField()),
                ('madre_trabaja', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='si', max_length=50)),
                ('madre_profesion', models.CharField(max_length=50)),
                ('madre_tipo_trabajo', models.CharField(max_length=50)),
                ('madre_domicilio', models.CharField(max_length=50)),
                ('madre_telefono', models.IntegerField()),
                ('ingresos_mensuales_f', models.FloatField()),
                ('ingresos_mensuales_p', models.FloatField()),
                ('donde_primaria', models.CharField(max_length=50)),
                ('donde_secundaria', models.CharField(max_length=50)),
                ('donde_bachillerato', models.CharField(max_length=50)),
                ('donde_estud_superiores', models.CharField(max_length=50)),
                ('prescripcion_medica', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=50)),
                ('prescripcion_medica_cuales', models.CharField(choices=[('vista', 'Vista'), ('oido', 'Oido'), ('lenguaje', 'Lenguaje'), ('otro', 'Otro')], default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='datoshermanos',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anexo8.FormatoEntrevista'),
        ),
    ]
