# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anexo8', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoshermanos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='datoshermanos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='influido_estudiar',
            field=models.CharField(choices=[('1', 'Pap\xe1'), ('2', 'Mam\xe1'), ('3', 'Hermano'), ('4', 'Hermana'), ('5', 'Tios')], max_length=50),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='ocupa_educacion',
            field=models.CharField(choices=[('1', 'Pap\xe1'), ('2', 'Mam\xe1'), ('3', 'Hermano'), ('4', 'Hermana'), ('5', 'Tios')], max_length=50),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='sientes_ligado',
            field=models.CharField(choices=[('1', 'Pap\xe1'), ('2', 'Mam\xe1'), ('3', 'Hermano'), ('4', 'Hermana'), ('5', 'Tios')], max_length=50),
        ),
    ]
