# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo8', '0002_auto_20160224_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaIntegracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion_familia', models.CharField(blank=True, choices=[('1', 'Muy buena'), ('2', 'Buena'), ('3', 'Regular'), ('4', 'Mala'), ('5', 'Muy mala')], max_length=50)),
                ('dificultades_fam', models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], max_length=50)),
                ('dificultades_fam_tipo', models.TextField()),
                ('actitud_con_familia', models.CharField(blank=True, choices=[('1', 'Muy buena'), ('2', 'Buena'), ('3', 'Regular'), ('4', 'Mala'), ('5', 'Muy mala')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='estadopsicofisiologicos',
            name='observaciones_higiene',
            field=models.CharField(default='', max_length=50),
        ),
    ]
