# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 16:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo8', '0002_auto_20160613_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoshermanos',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='estadopsicofisiologicos',
            old_name='incontinecia',
            new_name='incontinencia',
        ),
        migrations.RenameField(
            model_name='plandevida',
            old_name='miedo_aque',
            new_name='miedo_a_que',
        ),
        migrations.AlterField(
            model_name='areapsicopedagogica',
            name='promedio_anterior',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
