# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 17:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo8', '0003_auto_20160620_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areapsicopedagogica',
            name='promedio_anterior',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
