# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anexo8', '0004_auto_20160224_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaintegracion',
            name='actitud_con_adre',
        ),
        migrations.AddField(
            model_name='areaintegracion',
            name='sientes_ligado',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='anexo8.DatosHermanos'),
        ),
    ]
