# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo8', '0004_auto_20160620_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadopsicofisiologicos',
            old_name='perdidad_equilibrio',
            new_name='perdida_equilibrio',
        ),
        migrations.RenameField(
            model_name='formatoentrevista',
            old_name='estadovivienda',
            new_name='estado_vivienda',
        ),
        migrations.AlterField(
            model_name='datoshermanos',
            name='estudios',
            field=models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('tecnico', 'Tecnico'), ('lic', 'Licenciatura'), ('posgrado ', 'Posgrado'), ('sinestudio', 'Sin estudio')], max_length=50),
        ),
    ]
