# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo8', '0005_auto_20160224_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaintegracion',
            name='actitud_con_madre',
            field=models.CharField(choices=[('1', 'Muy buena'), ('2', 'Buena'), ('3', 'Regular'), ('4', 'Mala'), ('5', 'Muy mala')], default='2', max_length=50),
        ),
    ]
