# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo8', '0005_auto_20160727_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areapsicopedagogica',
            name='asig_reprovadas',
        ),
        migrations.RemoveField(
            model_name='areapsicopedagogica',
            name='asignaturas_reprovadas',
        ),
        migrations.AddField(
            model_name='areapsicopedagogica',
            name='asig_reprobadas',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='areapsicopedagogica',
            name='asignaturas_reprobadas',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=50),
        ),
    ]
