# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo8', '0007_auto_20160224_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaintegracion',
            name='act_recreativa',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='areaintegracion',
            name='relacion_autoridadesacademicas',
            field=models.CharField(choices=[('1', 'Muy buena'), ('2', 'Buena'), ('3', 'Regular'), ('4', 'Mala'), ('5', 'Muy mala')], default='2', max_length=50),
        ),
        migrations.AddField(
            model_name='areaintegracion',
            name='relacion_profesores',
            field=models.CharField(choices=[('1', 'Muy buena'), ('2', 'Buena'), ('3', 'Regular'), ('4', 'Mala'), ('5', 'Muy mala')], default='2', max_length=50),
        ),
        migrations.AddField(
            model_name='areaintegracion',
            name='tiempo_libre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
