# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo8', '0008_auto_20160224_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasPersonales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntual', models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50)),
                ('timido', models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50)),
                ('alegre', models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50)),
                ('agresivo', models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50)),
                ('abierto_ideas', models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50)),
                ('reflexivo', models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50)),
                ('constante', models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50)),
                ('optimista', models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50)),
                ('impulsivo', models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50)),
                ('silencioso', models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='formatoentrevista',
            name='estatura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='formatoentrevista',
            name='peso',
            field=models.FloatField(),
        ),
    ]
