# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo8', '0009_auto_20160224_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='activo',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='cambio_humor',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='confiado_simismo',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='dominante',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='egoista',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='generoso',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='imaginativo',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='independiente',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='iniciativa',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='inquieto',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='motivado',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='perseverante',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='responsable',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='sociable',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='sumiso',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Poco'), ('3', 'Frecuente'), ('4', 'Mucho')], default='1', max_length=50),
        ),
    ]
