# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo8', '0010_auto_20160224_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPsicopedagogica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gustaria_ser', models.CharField(max_length=50)),
                ('ayuda_casa_tareas', models.CharField(max_length=50)),
                ('problemas_intervienen', models.CharField(max_length=50)),
                ('rendimiento_escolar', models.CharField(max_length=50)),
                ('asignaturas_actual', models.TextField()),
                ('asignatura_preferida', models.CharField(max_length=50)),
                ('asignatura_preferida_porque', models.CharField(max_length=50)),
                ('asignatura_sobresales', models.CharField(max_length=50)),
                ('asignatura_sobresales_porque', models.CharField(max_length=50)),
                ('asignatura_desagrada', models.CharField(max_length=50)),
                ('asignatura_desagrada_porque', models.CharField(max_length=50)),
                ('asignatura_bajopromedio_anterior', models.CharField(max_length=50)),
                ('vienes_tecnologico', models.CharField(max_length=50)),
                ('motiva_venir_tecnologico', models.TextField()),
                ('promedio_anterior', models.FloatField()),
                ('asignaturas_reprovadas', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=50)),
                ('asig_reprovadas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDeVida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planes_inmediatos', models.TextField()),
                ('metas_vida', models.TextField()),
                ('yo_soy', models.TextField()),
                ('mi_caracter', models.TextField()),
                ('me_gusta_que', models.TextField()),
                ('aspiro_a_que', models.TextField()),
                ('miedo_aque', models.TextField()),
                ('podre_lograr_que', models.TextField()),
            ],
        ),
    ]
