# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo8', '0012_auto_20160225_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaintegracion',
            name='dificultades_fam_tipo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='influido_estudiar',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='ocupa_educacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='sientes_ligado_por',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='areapsicopedagogica',
            name='asig_reprovadas',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='datoshermanos',
            name='sexo',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=50),
        ),
        migrations.AlterField(
            model_name='formatoentrevista',
            name='prescripcion_medica_cuales',
            field=models.CharField(choices=[('vista', 'Vista'), ('oido', 'Oido'), ('lenguaje', 'Lenguaje'), ('otro', 'Otro')], max_length=50),
        ),
    ]
