# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 16:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anexo8', '0014_auto_20160418_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoshermanos',
            name='alumno',
        ),
        migrations.AddField(
            model_name='areaintegracion',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='areaintegracion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 11, 16, 38, 14, 629760, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areaintegracion',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 11, 16, 38, 19, 952740, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areapsicopedagogica',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='areapsicopedagogica',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 11, 16, 38, 24, 819566, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areapsicopedagogica',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 11, 16, 38, 30, 449884, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 11, 16, 38, 37, 483228, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristicaspersonales',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 11, 16, 39, 6, 450108, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datoshermanos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 11, 16, 39, 26, 883313, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datoshermanos',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 11, 16, 39, 31, 963155, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datoshermanos',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estadopsicofisiologicos',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='estadopsicofisiologicos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 11, 16, 39, 36, 887710, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadopsicofisiologicos',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 11, 16, 41, 33, 567742, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadopsicofisiologicos',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formatoentrevista',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='formatoentrevista',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 11, 16, 41, 38, 846530, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formatoentrevista',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 11, 16, 41, 56, 124964, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plandevida',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='plandevida',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 11, 16, 42, 2, 902448, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plandevida',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 11, 16, 42, 10, 346864, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
