# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 14:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fortaleza', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('oportunidad', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('debilidad', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('amenaza', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('comentario', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
