# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anexo10', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenazas',
            name='ayuda',
        ),
        migrations.RemoveField(
            model_name='debilidades',
            name='ayuda',
        ),
        migrations.RemoveField(
            model_name='fortalezas',
            name='ayuda',
        ),
        migrations.RemoveField(
            model_name='oportunidades',
            name='ayuda',
        ),
    ]
