# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 16:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anexo10', '0002_auto_20160418_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fortalezas', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('oportunidades', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('debilidades', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('amenazas', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('comentarios', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='amenazas',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='debilidades',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='fortalezas',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='oportunidades',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Amenazas',
        ),
        migrations.DeleteModel(
            name='Debilidades',
        ),
        migrations.DeleteModel(
            name='Fortalezas',
        ),
        migrations.DeleteModel(
            name='Oportunidades',
        ),
    ]
