# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 16:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anexo10', '0003_auto_20160511_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foda',
            name='amenazas',
        ),
        migrations.RemoveField(
            model_name='foda',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='foda',
            name='debilidades',
        ),
        migrations.RemoveField(
            model_name='foda',
            name='fortalezas',
        ),
        migrations.RemoveField(
            model_name='foda',
            name='oportunidades',
        ),
        migrations.AddField(
            model_name='foda',
            name='amenaza',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='foda',
            name='comentario',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='foda',
            name='debilidad',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='foda',
            name='fortaleza',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='foda',
            name='oportunidad',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
