# -*- coding: utf-8 -*-
etiquetas1=[
"¿Sueles dejar para el ultimo la preparación de tus trabajos?",
"¿Crees que el sueño o el cansancio te impida estudiar eficazmente en muchas ocasiones ?",
"¿Es frecuente que no termines tu tarea a tiempo?",
"¿Tiendes a emplear tiempo en leer revistas, ver televisión o charlar cuando debieras dedicarlo a estudiar?",
"Tus actividades sociales o deportivas.¿Te llevan a menudo a descuidar tus tareas escolares?",
"¿Sueles dejar pasar un día o más antes de repasar los apuntes tomados en clase?",
"¿Sueles dedicar tu tiempo libre entre las 4:00 de la tarde y a las 9:00 de la noche a otras actividades que no sean estudiar?",
"¿Descubres algunas veces de pronto,que debes entregar una tarea antes de lo que creías?",
"¿te retrasas, con frecuencia en una asignatura debido a que tienes que estudiar otra?",
"¿Te patrece que tu rendimiento es muy bajo en relación con el tiempo que dedicas al estudio",
"¿Está situado tu escritorio directamente frente a una ventana, puerta u otra fuente de distracción?",
"¿Sueles tener fotografías, trofeos o recuerdos sobre tu mesa de escritorio?",
"¿Sueles estudiar recostado en tu cama o arellanado con un asiento comodo?",
"¿Produce resplandor la lámpara que utilizas al estudiar?",
"Tu mesa de estudio ¿está tan desordenada y llena de objetos que no dispones de sitio suficiente para estudiar con eficacia?",
"¿Sueles interrumpir tu estudio por presonas que vienen a visitarte?",
"¿Estudias, con frecuencia miestras tienes puesta la televisión y/o la radio?",
"En el lugar donde estudias, ¿se pueden ver con facilidad revistas, fotos de jóvenes o materiales pertenecientes a tu afición?",
"¿Con frecuencia, interrumpen tu estudio actividades y ruidos que intervienen del exterior?",
"¿Suele hacerse lento tu estudio debido a que no tienes a la mano los libros y los materiales necesarios?"]

etiquetas2=[
"¿Tiendes a comenzar la lectura de un libro de texto sin hojear previamente los subtitulos y las instrucciones?",
"¿Te saltas por lo general las figuras, graficas y tablas cuando estudias un tema?",
"¿Suele serte dificil seleccionar los puntoos de los temas de estudio?",
"¿Te sorprendes con una cierta frecuencia, pensando en algo que no tiene nada que ver con lo que estudias?",
"¿Sueles tener dificultad en entender tus apuntes de clases cuando tratas de repasarlos, despues de cierto tiempo?",
"Al tomar notas,¿te sueles quedar atras con frecuencia debido a que no puedes escribir con suficiente rapidez?",
"Poco despue de comenzar un curso,¿Sueles encontrarte con tus apuntes formando un 'revoltijo' ?",
"¿Tomas normalmente tus apuntes tratando de scribir las palabras exactas del docente?",
"Cuando tomas notas de un libro,¿Tienes la costumbre de copiar el material necesario, palabra por palabra?",
"¿Te es dificil preparar un temario apropiado para una evaluación?",
"¿Tienes problemas para organizar los datos o el contenido de una evaluación?",
"¿Al repasar el temario de una evaluación formulas un resumen de este?",
"¿Te preparas aveces para una evaluación memorizando fórmulas, definiciones o reglas que no entiendes con claridad?",
"¿Te resulta difícil decidir qué estudiar y como estudiarlo cuando pre?",
"¿Sueles tener dificultades para organizar, un orden lógico, las asignaturas que debes estudiar por temas?",
"Al preparar evaluación,¿Sueles estudiar toda la asignatura, en el ultimo momento?",
"¿Sueles entregar tus exámenes sin revisarlos detenidamente para ver si tienen algún error cometido por descuido?",
"¿Te es posible con frecuencia terminar una evaluación de exposición de un tema en el tiempo prescrito?",
"¿Sueles perder puntos en exámenes con preguntas de 'Verdadero-Falso',debido a que no lees detenidamente?",
"¿Empleas normalmente mucho tiempo en contestar la primera mitad de la prueva y tienes que apresurarte en la segunda?"
]

etiquetas3=[
"Despues de los primeros días o semanas del curso,¿Tiendes a perder interés por el estudio?",
"¿Crees que en general, basta estudiar lo necesasrio para obtener un 'aprobado' en las asignaturas?",
"¿Te sientes frecuentemente confuso e indeciso sobre cuáles deben ser tus metas formativas y profesionales?",
"¿Sueles pensar que no vale la pena el tiempo y el esfuerzo que son necesarios para lograr una educación universitaria?",
"¿Crees que es mas importante divertirte y disfrutar de la vida, que estudiar?",
"¿Sueles pasar el tiempo de clases en divagaciones o soñando despierto en lugar de atender al docente?",
"¿Te sientes habitualmente incapaz de consentrarte en tus estudios debido a que estas inquieto , aburrido o de mal humor ?",
"¿Piensas con frecuencia que las asignatuas que estudias tienen poco valor practico para ti?",
"¿Sientes, frecuntes deseos de abandonar la escuela y conseguir un trabajo?",
"¿Sueles tener la sensación de lo que se enseña en los centros docentes no te prepara para afrontar los problemas de la vida adulta?",
"¿Suele dedicarte de modo casual según el estado de ánimo en que te encuentres?",
"¿Te horroriza estudiar libros de textos por que son insípidos y aburridos?",
"¿Esperas normalmente que te fijen la fecha de evaluación para comenzar a estudiar los textos o a repasar tus apuntes de clases?",
"¿Sueles pensar que los examenes son pruevas penosas que no se puede escapar y respecto a las cuales lo que se debe hacerse es sobrevivir, del modo que sea?",
"¿Sientes con frecuencia que tus docentes no comprenden las necesidades de los estudiantes?",
"¿Tienes normalmente la sensación que los docentes exigen demaciadas horas de estudio fuera de clases?",
"¿Dudas por lo general en pedir ayuda a tus docentes en tareas que te son difíciles?",
"¿Sueles pensar que tus docentes no tienen contacto con los temas y sucesos de la actualidad?",
"¿Te sientes reacio, por lo general, a hablar con tus docentes de tus proyectos futuros , de estudio o profecionales?",
"¿Criticas con frecuencia a tus docentes cuando hablas con tus compañeros?"
]
