# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 14:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAsertividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pregunta1', models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'En una reuni\xc3\xb3n dificil, con con un ambiente tenso,soy capaz de hablar con confianza')),
                ('pregunta2', models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Si no estoy seguro(a) de una cosa, puedo pedir ayuda facilmente.')),
                ('pregunta3', models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Si alguna persona es injusta y agresiva, puedo controlar la situaci\xc3\xb3n con confianza')),
                ('pregunta4', models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'si alguna persona se muestra ir\xc3\xb3nica conmigo o con otros, puedo responder sin agresividad')),
                ('pregunta5', models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Si creo que se esta abusando de mi, soy capaz de denunciarlo sin alterarme')),
                ('pregunta6', models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Si alguna persona me pide permiso para hacer algo que no me gusta, por ejemplo, fumar, puedo decirle que no sin sentirme culpable')),
                ('pregunta7', models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Si alguna persona pide mi opini\xc3\xb3n sobre alguna cosa me siento bien dandosela, aunque no concuerde con la de los dem\xc3\xa1s')),
                ('pregunta8', models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Puedo conectar f\xc3\xa1cil y efectivamente con personas que considero importantes')),
                ('pregunta9', models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Cuando encuentro defectos en una tienda o restaurante, soy capaz de exponerlos sin atacar a las otras personas y sin sentirme mal')),
                ('diagnostico', models.CharField(blank=True, choices=[('1', 'Paso el Test de asertividad'), ('0', 'No paso el Test de asertividad')], max_length=2)),
                ('comentarios', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
