# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 14:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anexo13', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testasertividad',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
