# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo13', '0002_auto_20160512_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta1',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'En una reuni\xc3\xb3n dificil, con con un ambiente tenso, soy capaz de hablar con confianza'),
        ),
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta4',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Si alguna persona se muestra ir\xc3\xb3nica conmigo o con otros, puedo responder sin agresividad'),
        ),
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta6',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Si alguna persona me pide permiso para hacer algo que no me gusta, por ejemplo, fumar. Puedo decirle que no sin sentirme culpable'),
        ),
    ]
