# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo13', '0008_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta1',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2),
        ),
    ]
