# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo13', '0009_auto_20160317_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testasertividad',
            name='diagnostico',
            field=models.CharField(blank=True, choices=[('1', 'Paso el Test de asertividad'), ('0', 'No paso el Test de asertividad')], max_length=2),
        ),
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta1',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name='En una reuni\xf3n dficil, con con un ambiente tenso,soy capaz de hablar con confianza'),
        ),
    ]
