# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo13', '0010_auto_20160404_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta1',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'En una reuni\xc3\xb3n dicil, con con un ambiente tenso,soy capaz de hablar con confianza'),
        ),
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta3',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Si alguna persona es injusta y agresiva, puedo controlar la situacion con confianza'),
        ),
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta5',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Si creo que se esta abusando de mi, soy capaz de denunciarlo sin alterarme'),
        ),
    ]
