# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo13', '0011_auto_20160425_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta1',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'En una reuni\xc3\xb3n dificil, con con un ambiente tenso,soy capaz de hablar con confianza'),
        ),
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta2',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Si no estoy seguro(a) de una cosa, puedo pedir ayuda facilmente.'),
        ),
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta3',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Si alguna persona es injusta y agresiva, puedo controlar la situaci\xc3\xb3n con confianza'),
        ),
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta4',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'si alguna persona se muestra ir\xc3\xb3nica conmigo o con otros, puedo responder sin agresividad'),
        ),
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta7',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Si alguna persona pide mi opini\xc3\xb3n sobre alguna cosa me siento bien dandosela, aunque no concuerde con la de los dem\xc3\xa1s'),
        ),
        migrations.AlterField(
            model_name='testasertividad',
            name='pregunta8',
            field=models.CharField(choices=[('1', 'Con Frecuencia'), ('2', 'De vez en cuando'), ('3', 'Casi nunca'), ('4', 'Nunca')], default='4', max_length=2, verbose_name=b'Puedo conectar f\xc3\xa1cil y efectivamente con personas que considero importantes'),
        ),
    ]
