# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 16:42
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anexo13', '0012_auto_20160426_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='tutorado',
        ),
        migrations.AddField(
            model_name='testasertividad',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='testasertividad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 11, 16, 36, 36, 970775, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testasertividad',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 11, 16, 37, 7, 585977, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
