# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo12', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta1',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=2, verbose_name=b'A la hora de tomar decisiones en tu vida, como proponer cosas nuevas en el trabajo, iniciar alguna actividad de ocio, o elegir un color nuevo para pintar tu casa, \xc2\xbfsueles buscar la aprobaci\xc3\xb3n o el apoyo de las personas que te rodean?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta10',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=2, verbose_name=b'En una fiesta en La que no conoces a nadie excepto a Los anfitriones, te presentan a un grupo de personas de aspecto interesante. \xc2\xbfCu\xc3\xa1l es tu actitud?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta2',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=2, verbose_name=b'Imagina que est\xc3\xa1s en una reuni\xc3\xb3n social o familiar importante; adviertes que 110 vas vestido para la ocasi\xc3\xb3n y que desentonas con los dem\xc3\xa1s, \xc2\xbfc\xc3\xb3mo te comportas?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta3',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=2, verbose_name=b'Tienes muchas ganas de irte a comprar ropa y le pides a alg\xc3\xban amigo que te acompa\xc3\xb1e. Esta persona es m\xc3\xa1s alta y m\xc3\xa1s atractiva que t\xc3\xba, y todo lo que se prueba le queda mucho mejor que a ti.'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta4',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=2, verbose_name=b'Un d\xc3\xada conoces a alguien nuevo y muy interesante, est\xc3\xa1is charlando animadamente y llega el momento de hablar de ti, \xc2\xbfcu\xc3\xa1l de las siguientes opciones mejor se ajusta a lo que cuentas?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta5',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=2, verbose_name=b'En tu lugar de trabajo o de estudios, se est\xc3\xa1 explicando algo que es completamente nuevo para ti. Llega un momento en que te das cuenta que no has entendido casi nada \xc2\xbfqu\xc3\xa9 haces?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta6',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=2, verbose_name=b'Tener un trabajo bien remunerado y que nos guste es algo dif\xc3\xadcil de conseguir, si tuvieras que valorar tu empleo o tu situaci\xc3\xb3n laboral, \xc2\xbfc\xc3\xb3mo la definir\xc3\xadas?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta7',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=2, verbose_name=b'Has tenido un d\xc3\xada duro, has trabajado con m\xc3\xa1s ah\xc3\xadnco para finalizar una tarea en la oficina, has hecho todas las gestiones que ten\xc3\xadas pendientes, has resuelto un par de problemas dom\xc3\xa9sticos y encima le has hecho un favor a un amigo. \xc2\xbfQu\xc3\xa9 haces al llegar a casa?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta8',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=2, verbose_name=b'En tu trabajo est\xc3\xa1n buscando a una persona que represente a la empresa en un concurso del ramo. Piden una persona que cumpla unos requisitos, entre ellos, explicar bien vuestro trabajo y que haga una demostraci\xc3\xb3n pr\xc3\xa1ctica del mismo.'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta9',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=2, verbose_name=b'\xc2\xbfCon cu\xc3\xa1l de las siguientes frases sobre la buena fortuna est\xc3\xa1s m\xc3\xa1s de acuerdo?'),
        ),
    ]
