# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo12', '0002_auto_20160712_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta1',
            field=models.CharField(choices=[(b'4', b'A) No, consideras que tu opini\xc3\xb3n sea buena y que la de los dem\xc3\xa1s no tenga por qu\xc3\xa9 serlo siempre.'), (b'2', b'B) S\xc3\xad, pero s\xc3\xb3lo ante las decisiones que consideras demasiado importantes como para actuar precipitadamente.'), (b'1', b'C) S\xc3\xad, siempre que puedes consultas con los dem\xc3\xa1s. Te equivocas con frecuencia y quieres hacer las cosas bien.'), (b'3', b'D) Depende de la decisi\xc3\xb3n. Sueles tener claro lo que vas a hacer, pero consideras las posibilidades que te ofrecen los dem\xc3\xa1s.')], max_length=2, verbose_name=b'A la hora de tomar decisiones en tu vida, como proponer cosas nuevas en el trabajo, iniciar alguna actividad de ocio, o elegir un color nuevo para pintar tu casa, \xc2\xbfsueles buscar la aprobaci\xc3\xb3n o el apoyo de las personas que te rodean?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta10',
            field=models.CharField(choices=[(b'3', b'A) Te interesa conocerlos no s\xc3\xb3lo para pasar un buen rato en la reuni\xc3\xb3n sino porque puede ser una forma de iniciar una amistad.'), (b'1', b'B) Esperas causarles una buena impresi\xc3\xb3n y decir cosas que les puedan interesar.'), (b'4', b'C) Te gustar\xc3\xada llevarles a tu terreno en la conversaci\xc3\xb3n para as\xc3\xad poder hablar de los temas que m\xc3\xa1s te interesan.'), (b'2', b'D) Antes de iniciar una conversaci\xc3\xb3n escuchas lo que dicen, y es peras para hablar a que lo hagan de temas que t\xc3\xba conozcas.')], max_length=2, verbose_name=b'En una fiesta en La que no conoces a nadie excepto a Los anfitriones, te presentan a un grupo de personas de aspecto interesante. \xc2\xbfCu\xc3\xa1l es tu actitud?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta2',
            field=models.CharField(choices=[(b'3', b'A) No le das importancia, te comportas con naturalidad y si alguien te lo comenta haces alguna broma al respecto.'), (b'1', b'B) Te da mucha verg\xc3\xbcenza. Procuras situarte en alg\xc3\xban lugar discreto y pasar desapercibido.'), (b'4', b'C) Te sientes inc\xc3\xb3modo pero tratas de no pensar en ello, te integras en la reuni\xc3\xb3n y das alguna excusa por tu error.'), (b'1', b'D) No te importa nada en absoluto, aunque no lleves la ropa adecuada tienes estilo y sabes llevar bien cualquier cosa.')], max_length=2, verbose_name=b'Imagina que est\xc3\xa1s en una reuni\xc3\xb3n social o familiar importante; adviertes que 110 vas vestido para la ocasi\xc3\xb3n y que desentonas con los dem\xc3\xa1s, \xc2\xbfc\xc3\xb3mo te comportas?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta3',
            field=models.CharField(choices=[(b'2', b'A) Admiras el estilo de tu acompa\xc3\xb1ante, al final compras un par de prendas necesarias pero muy simples en cuanto a forma y color.'), (b'4', b'B) No est\xc3\xa1s dispuesto a que te gane, decides comprar varias prendas muy modernas y bastante caras.'), (b'3', b'C) Admiras su estilo pero eres muy consciente del tuyo, compras la ropa que mejor te sienta y que necesitas, y pas\xc3\xa1is un rato ameno prob\xc3\xa1ndoos cosas diferentes.'), (b'1', b'D) A su lado te sientes bastante poca cosa, te quita las ganas de probarte nada y mucho menos de comprar. Pones una excusa y te marchas.')], max_length=2, verbose_name=b'Tienes muchas ganas de irte a comprar ropa y le pides a alg\xc3\xban amigo que te acompa\xc3\xb1e. Esta persona es m\xc3\xa1s alta y m\xc3\xa1s atractiva que t\xc3\xba, y todo lo que se prueba le queda mucho mejor que a ti.'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta4',
            field=models.CharField(choices=[(b'1', b'A) No crees que tengas mucho que contar, tu trabajo es muy corriente, tus amigos son normales y tus aficiones tambi\xc3\xa9n. Prefieres que esta persona te cuente su vida.'), (b'3', b'B) Tu trabajo te gusta y aunque sea corriente, siempre lo enfocas desde una perspectiva interesante, tus aficiones son tu pasi\xc3\xb3n y disfrutas hablando de ellas, tambi\xc3\xa9n hablas de tus proyectos futuros.'), (b'2', b'C) Hablas en l\xc3\xadneas generales de tu trabajo y de tus aficiones, sobre todo hablas de tus amigos y de lo m\xc3\xa1s interesante de sus vidas.'), (b'4', b'D) M\xc3\xa1s que de tu trabajo actual, hablas de tus proyectos y de tus objetivos, y de lo que vas a hacer para logrados, de lo buenas que son tus amistades y lo poco usual de tus aficiones. Te gusta hablar de ti.')], max_length=2, verbose_name=b'Un d\xc3\xada conoces a alguien nuevo y muy interesante, est\xc3\xa1is charlando animadamente y llega el momento de hablar de ti, \xc2\xbfcu\xc3\xa1l de las siguientes opciones mejor se ajusta a lo que cuentas?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta5',
            field=models.CharField(choices=[(b'4', b'A) Paras la explicaci\xc3\xb3n y requieres que se empiece de nuevo, si tu no lo entiendes habr\xc3\xa1 mucha gente que tampoco lo haga.'), (b'2', b'B) Si hay m\xc3\xa1s gente que pregunte tu tambi\xc3\xa9n lo haces, si no, buscas en un aparte al ponente para que te aclare las dudas.'), (b'1', b'C) Te da mucha verg\xc3\xbcenza preguntar y demostrar as\xc3\xad que no entiendes. M\xc3\xa1s tarde preguntar\xc3\xa1s a alg\xc3\xban amigo o intentar\xc3\xa1s informarte por tu cuenta.'), (b'3', b'D) Tomas nota de lo que no entiendes para preguntarlo al finalizar la charla, si sigues con dudas pedir\xc3\xa1s informaci\xc3\xb3n complementaria para prepararte mejor.')], max_length=2, verbose_name=b'En tu lugar de trabajo o de estudios, se est\xc3\xa1 explicando algo que es completamente nuevo para ti. Llega un momento en que te das cuenta que no has entendido casi nada \xc2\xbfqu\xc3\xa9 haces?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta6',
            field=models.CharField(choices=[(b'3', b'A) Satisfactoria, tratas de buscar el lado positivo de las cosas y nunca te faltan proyectos y objetivos que perseguir.'), (b'1', b'B) Horrible, no obstante, sabes que las cosas est\xc3\xa1n mal y que tienes que aguantar lo que sea. Est\xc3\xa1s muy agradecido por tener trabajo.'), (b'4', b'C) No te preocupa especialmente el tema, tienes un mont\xc3\xb3n de proyectos m\xc3\xa1s importantes y con tu val\xc3\xada los alcanzar\xc3\xa1s.'), (b'2', b'D) Has logrado que no te afecte, consideras m\xc3\xa1s importante tu vida personal y privada y eso es por lo que luchas.')], max_length=2, verbose_name=b'Tener un trabajo bien remunerado y que nos guste es algo dif\xc3\xadcil de conseguir, si tuvieras que valorar tu empleo o tu situaci\xc3\xb3n laboral, \xc2\xbfc\xc3\xb3mo la definir\xc3\xadas?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta7',
            field=models.CharField(choices=[(b'2', b'A) Prefieres no pensarlo, el d\xc3\xada ha sido duro pero para ti no es algo nuevo, solo pides poder dormir bien y que ma\xc3\xb1ana sea un d\xc3\xada m\xc3\xa1s tranquilo.'), (b'4', b'B) Se lo cuentas a todo el mundo, te gusta que se te reconozca cuando haces las cosas bien y exiges en casa que te mimen por haberte esforzado tanto.'), (b'3', b'C) Est\xc3\xa1s muy satisfecho y decides darte un capricho, darte un ba\xc3\xb1o de espuma y ver una buena pel\xc3\xadcula, o comprarte un regalito que hace tiempo quer\xc3\xadas.'), (b'1', b'D) Te preocupa que se te haya olvidado algo o haber hecho algo mal por la prisa, repasas mentalmente las actividades y al d\xc3\xada siguiente esperas no tener queja de nadie.')], max_length=2, verbose_name=b'Has tenido un d\xc3\xada duro, has trabajado con m\xc3\xa1s ah\xc3\xadnco para finalizar una tarea en la oficina, has hecho todas las gestiones que ten\xc3\xadas pendientes, has resuelto un par de problemas dom\xc3\xa9sticos y encima le has hecho un favor a un amigo. \xc2\xbfQu\xc3\xa9 haces al llegar a casa?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta8',
            field=models.CharField(choices=[(b'1', b'A) No te planteas ser voluntario, hay mil personas m\xc3\xa1s capacitadas que t\xc3\xba para la demostraci\xc3\xb3n y no se te da bien hablar en p\xc3\xbablico.'), (b'3', b'B) Te presentas voluntario, puede ser una experiencia interesante y si sales elegido puedes hacer una presentaci\xc3\xb3n innovadora.'), (b'1', b'C) No te presentas, ser\xc3\xadas capaz de hacerla bien pero crees que hay gente mejor preparada y m\xc3\xa1s original que t\xc3\xba.'), (b'4', b'D) Te presentas y est\xc3\xa1s casi seguro de que te elegir\xc3\xa1n, haces buenos proyectos y dar\xc3\xa1s una buena imagen de la empresa.')], max_length=2, verbose_name=b'En tu trabajo est\xc3\xa1n buscando a una persona que represente a la empresa en un concurso del ramo. Piden una persona que cumpla unos requisitos, entre ellos, explicar bien vuestro trabajo y que haga una demostraci\xc3\xb3n pr\xc3\xa1ctica del mismo.'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta9',
            field=models.CharField(choices=[(b'4', b'A) La buena suerte puede tocarle a todo el mundo, yo me considero una persona afortunada a la que la vida le sonr\xc3\xade.'), (b'2', b'B) Para tener buena suerte hay que trabajar duro, s\xc3\xb3lo los muy afortunados la tienen sin apenas esfuerzo.'), (b'1', b'C) Yo no tengo suerte, tanto los premios como las cosas especia les s\xc3\xb3lo les pasan a los dem\xc3\xa1s.'), (b'3', b'D) La suerte respecto a los premios es una cuesti\xc3\xb3n de probabilidad, y respecto a las cosas de la vida, siempre depende de c\xc3\xb3mo se perciban.')], max_length=2, verbose_name=b'\xc2\xbfCon cu\xc3\xa1l de las siguientes frases sobre la buena fortuna est\xc3\xa1s m\xc3\xa1s de acuerdo?'),
        ),
    ]
