# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo12', '0003_auto_20160714_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta1',
            field=models.CharField(choices=[(b'4', b'A) No, consideras que tu opini\xc3\xb3n sea buena y que la de los dem\xc3\xa1s no tenga por qu\xc3\xa9 serlo siempre.'), (b'2', b'B) S\xc3\xad, pero s\xc3\xb3lo ante las decisiones que consideras demasiado importantes como para actuar precipitadamente.'), (b'1', b'C) S\xc3\xad, siempre que puedes consultas con los dem\xc3\xa1s. Te equivocas con frecuencia y quieres hacer las cosas bien.'), (b'3', b'D) Depende de la decisi\xc3\xb3n. Sueles tener claro lo que vas a hacer, pero consideras las posibilidades que te ofrecen los dem\xc3\xa1s.')], max_length=2, verbose_name=b'A la hora de tomar decisiones en tu vida, como proponer cosas nuevas en el trabajo, iniciar alguna actividad de ocio, o elegir un color nuevo para pintar tu casa, \xc2\xbfSueles buscar la aprobaci\xc3\xb3n o el apoyo de las personas que te rodean?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta10',
            field=models.CharField(choices=[(b'3', b'A) Te interesa conocerlos no s\xc3\xb3lo para pasar un buen rato en la reuni\xc3\xb3n sino porque puede ser una forma de iniciar una amistad.'), (b'1', b'B) Esperas causarles una buena impresi\xc3\xb3n y decir cosas que les puedan interesar.'), (b'4', b'C) Te gustar\xc3\xada llevarles a tu terreno en la conversaci\xc3\xb3n para as\xc3\xad poder hablar de los temas que m\xc3\xa1s te interesan.'), (b'2', b'D) Antes de iniciar una conversaci\xc3\xb3n escuchas lo que dicen, y es peras para hablar a que lo hagan de temas que t\xc3\xba conozcas.')], max_length=2, verbose_name=b'En una fiesta en la que no conoces a nadie excepto a los anfitriones, te presentan a un grupo de personas de aspecto interesante. \xc2\xbfCu\xc3\xa1l es tu actitud?'),
        ),
        migrations.AlterField(
            model_name='testautoestima',
            name='pregunta4',
            field=models.CharField(choices=[(b'1', b'A) No crees que tengas mucho que contar, tu trabajo es muy corriente, tus amigos son normales y tus aficiones tambi\xc3\xa9n. Prefieres que esta persona te cuente su vida.'), (b'3', b'B) Tu trabajo te gusta y aunque sea corriente, siempre lo enfocas desde una perspectiva interesante, tus aficiones son tu pasi\xc3\xb3n y disfrutas hablando de ellas, tambi\xc3\xa9n hablas de tus proyectos futuros.'), (b'2', b'C) Hablas en l\xc3\xadneas generales de tu trabajo y de tus aficiones, sobre todo hablas de tus amigos y de lo m\xc3\xa1s interesante de sus vidas.'), (b'4', b'D) M\xc3\xa1s que de tu trabajo actual, hablas de tus proyectos y de tus objetivos, y de lo que vas a hacer para logrados, de lo buenas que son tus amistades y lo poco usual de tus aficiones. Te gusta hablar de ti.')], max_length=2, verbose_name=b'Un d\xc3\xada conoces a alguien nuevo y muy interesante, est\xc3\xa1s charlando animadamente y llega el momento de hablar de ti, \xc2\xbfcu\xc3\xa1l de las siguientes opciones mejor se ajusta a lo que cuentas?'),
        ),
    ]
