# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 14:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('otro', 'Otro')], default='soltero', max_length=50)),
                ('numero_hijos', models.IntegerField(blank=True, null=True)),
                ('domicilio_actual', models.CharField(default='', max_length=50)),
                ('escolaridad', models.CharField(choices=[('preparatoria', 'Preparatoria'), ('bachillerato_tec', 'Bachillerato T\xe9cnico')], default='preparatoria', max_length=50)),
                ('nombre_institucion', models.CharField(default='', max_length=50)),
                ('becado', models.CharField(choices=[('si', 'S\xed'), ('no', 'No')], default='no', max_length=50)),
                ('becado_lugar', models.CharField(blank=True, choices=[('federal', 'Gobierno Federal'), ('estatal', 'Gobierno Estatal'), ('bachillerato', 'Esfuerzo de bachillerato')], default='federal', max_length=50)),
                ('becado_institucion', models.CharField(default='', max_length=50)),
                ('conquien_vives', models.CharField(choices=[('familia', 'Familia'), ('faminia_cercana', 'Familia Cercana'), ('estudiantes', 'Estudiantes'), ('solo', 'Solo')], default='familia', max_length=50)),
                ('trabajas', models.CharField(choices=[('si', 'S\xed'), ('no', 'No')], default='no', max_length=50)),
                ('trabajas_donde', models.CharField(default='', max_length=50)),
                ('trabajas_horario_inicio', models.TimeField(null=True)),
                ('trabajas_horario_salida', models.TimeField(null=True)),
                ('escolaridad_padre', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('tecnico', 'Tecnico'), ('lic', 'Lic'), ('posgrado ', 'Posgrado'), ('sinestudio', 'Sin estudio')], default='sinestudio', max_length=50)),
                ('escolaridad_madre', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('tecnico', 'Tecnico'), ('lic', 'Lic'), ('posgrado ', 'Posgrado'), ('sinestudio', 'Sin estudio')], default='sinestudio', max_length=50)),
                ('padre_vive', models.CharField(choices=[('si', 'Vive'), ('no', 'Finado')], default='si', max_length=50)),
                ('madre_vive', models.CharField(choices=[('si', 'Vive'), ('no', 'Finado')], default='si', max_length=50)),
                ('nom_trabajo_padre', models.CharField(default='', max_length=50)),
                ('nom_trabajo_madre', models.CharField(default='', max_length=50)),
                ('ContactosEmergencia', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('carrera', models.CharField(max_length=30)),
                ('numero_control', models.CharField(max_length=50)),
                ('semestre', models.IntegerField()),
                ('fecha', models.DateField()),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
