# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=30)),
                ('numero_control', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
