# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anexo6', '0002_datosgenerales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactosEmergencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='becado',
            field=models.CharField(choices=[('si', 'S\xed'), ('no', 'No')], default='no', max_length=50),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='becado_lugar',
            field=models.CharField(choices=[('federal', 'Gobierno Federal'), ('estatal', 'Gobierno Estatal'), ('bachillerato', 'Esfuerzo de bachillerato')], default='federal', max_length=50),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='conquien_vives',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='domicilio_actual',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='escolaridad',
            field=models.CharField(choices=[('preparatoria', 'Preparatoria'), ('bachillerato_tec', 'Bachillerato T\xe9cnico')], default='preparatoria', max_length=50),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='nom_trabajo_madre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='nom_trabajo_padre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='nombre_institucion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='trabajas_horario_inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='trabajas_horario_salida',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado')], default='soltero', max_length=50),
        ),
        migrations.AddField(
            model_name='contactosemergencia',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anexo6.DatosGenerales'),
        ),
    ]
