# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo6', '0003_auto_20160727_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
