# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo6', '0003_auto_20160216_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgenerales',
            name='trabajas',
            field=models.CharField(choices=[('si', 'S\xed'), ('no', 'No')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='becado_lugar',
            field=models.CharField(blank=True, choices=[('federal', 'Gobierno Federal'), ('estatal', 'Gobierno Estatal'), ('bachillerato', 'Esfuerzo de bachillerato')], default='federal', max_length=50),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='conquien_vives',
            field=models.CharField(choices=[('familia', 'Familia'), ('faminia_cercana', 'Familia Cercana'), ('estudiantes', 'Estudiantes'), ('solo', 'Solo')], default='familia', max_length=50),
        ),
    ]
