# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo6', '0004_auto_20160920_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgenerales',
            name='celular',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
