# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo6', '0004_auto_20160216_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgenerales',
            name='trabajas_donde',
            field=models.CharField(default='', max_length=50),
        ),
    ]
