# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo6', '0005_datosgenerales_trabajas_donde'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgenerales',
            name='escolaridad_madre',
            field=models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('tecnico', 'Tecnico'), ('lic', 'Lic'), ('posgrado ', 'Posgrado'), ('sinestudio', 'Sin estudio')], default='sinestudio', max_length=50),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='escolaridad_padre',
            field=models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('tecnico', 'Tecnico'), ('lic', 'Lic'), ('posgrado ', 'Posgrado'), ('sinestudio', 'Sin estudio')], default='sinestudio', max_length=50),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='madre_vive',
            field=models.CharField(choices=[('si', 'Vive'), ('no', 'Finado')], default='si', max_length=50),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='padre_vive',
            field=models.CharField(choices=[('si', 'Vive'), ('no', 'Finado')], default='si', max_length=50),
        ),
    ]
