# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anexo6', '0005_auto_20160920_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosgenerales',
            name='ContactosEmergencia',
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='Contacto_de_Emergencia_nombre',
            field=models.CharField(default=datetime.datetime(2016, 9, 20, 13, 43, 58, 338280, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='Contacto_de_Emergencia_numero',
            field=models.CharField(default=datetime.datetime(2016, 9, 20, 13, 44, 8, 326845, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
