# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo6', '0006_auto_20160920_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgenerales',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
