# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anexo6', '0007_auto_20160920_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='fecha',
        ),
    ]
