# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 16:42
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anexo6', '0008_auto_20160418_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactosemergencia',
            name='usuario',
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='ContactosEmergencia',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 11, 16, 37, 35, 774126, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 11, 16, 37, 48, 738578, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 11, 16, 38, 0, 523031, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 11, 16, 38, 8, 809432, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContactosEmergencia',
        ),
    ]
