# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizacionEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta2', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta3', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta4', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta5', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta6', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta7', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta8', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta9', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta10', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta11', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta12', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta13', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta14', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta15', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta16', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta17', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta18', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta19', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('pregunta20', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=2, verbose_name='preguntas')),
                ('diagnostico', models.CharField(blank=True, choices=[('0', 'Muy bajo'), ('1', 'bajo'), ('2', 'Por debajo del promedio'), ('3', 'Promedio bajo'), ('4', 'Promedio'), ('5', 'Promedio alto'), ('6', 'Por encima del promedio'), ('7', 'alto'), ('8', 'muy alto')], max_length=2)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
