# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 14:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivacionEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pregunta1', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Despues de los primeros d\xc3\xadas o semanas del curso,\xc2\xbfTiendes a perder inter\xc3\xa9s por el estudio?')),
                ('pregunta2', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b"\xc2\xbfCrees que en general, basta estudiar lo necesasrio para obtener un 'aprobado' en las asignaturas?")),
                ('pregunta3', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe sientes frecuentemente confuso e indeciso sobre cu\xc3\xa1les deben ser tus metas formativas y profesionales?')),
                ('pregunta4', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles pensar que no vale la pena el tiempo y el esfuerzo que son necesarios para lograr una educaci\xc3\xb3n universitaria?')),
                ('pregunta5', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfCrees que es mas importante divertirte y disfrutar de la vida, que estudiar?')),
                ('pregunta6', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles pasar el tiempo de clases en divagaciones o so\xc3\xb1ando despierto en lugar de atender al docente?')),
                ('pregunta7', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe sientes habitualmente incapaz de consentrarte en tus estudios debido a que estas inquieto , aburrido o de mal humor ?')),
                ('pregunta8', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfPiensas con frecuencia que las asignatuas que estudias tienen poco valor practico para ti?')),
                ('pregunta9', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSientes, frecuntes deseos de abandonar la escuela y conseguir un trabajo?')),
                ('pregunta10', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles tener la sensaci\xc3\xb3n de lo que se ense\xc3\xb1a en los centros docentes no te prepara para afrontar los problemas de la vida adulta?')),
                ('pregunta11', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSuele dedicarte de modo casual seg\xc3\xban el estado de \xc3\xa1nimo en que te encuentres?')),
                ('pregunta12', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe horroriza estudiar libros de textos por que son ins\xc3\xadpidos y aburridos?')),
                ('pregunta13', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfEsperas normalmente que te fijen la fecha de evaluaci\xc3\xb3n para comenzar a estudiar los textos o a repasar tus apuntes de clases?')),
                ('pregunta14', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles pensar que los examenes son pruevas penosas que no se puede escapar y respecto a las cuales lo que se debe hacerse es sobrevivir, del modo que sea?')),
                ('pregunta15', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSientes con frecuencia que tus docentes no comprenden las necesidades de los estudiantes?')),
                ('pregunta16', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTienes normalmente la sensaci\xc3\xb3n que los docentes exigen demaciadas horas de estudio fuera de clases?')),
                ('pregunta17', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfDudas por lo general en pedir ayuda a tus docentes en tareas que te son dif\xc3\xadciles?')),
                ('pregunta18', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles pensar que tus docentes no tienen contacto con los temas y sucesos de la actualidad?')),
                ('pregunta19', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe sientes reacio, por lo general, a hablar con tus docentes de tus proyectos futuros , de estudio o profecionales?')),
                ('pregunta20', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfCriticas con frecuencia a tus docentes cuando hablas con tus compa\xc3\xb1eros?')),
                ('diagnostico', models.CharField(blank=True, choices=[('0', 'Muy bajo'), ('1', 'bajo'), ('2', 'Por debajo del promedio'), ('3', 'Promedio bajo'), ('4', 'Promedio'), ('5', 'Promedio alto'), ('6', 'Por encima del promedio'), ('7', 'alto'), ('8', 'muy alto')], max_length=2)),
                ('comentarios', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizacionEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pregunta1', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles dejar para el ultimo la preparaci\xc3\xb3n de tus trabajos?')),
                ('pregunta2', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfCrees que el sue\xc3\xb1o o el cansancio te impida estudiar eficazmente en muchas ocasiones ?')),
                ('pregunta3', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfEs frecuente que no termines tu tarea a tiempo?')),
                ('pregunta4', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTiendes a emplear tiempo en leer revistas, ver televisi\xc3\xb3n o charlar cuando debieras dedicarlo a estudiar?')),
                ('pregunta5', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Tus actividades sociales o deportivas.\xc2\xbfTe llevan a menudo a descuidar tus tareas escolares?')),
                ('pregunta6', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles dejar pasar un d\xc3\xada o m\xc3\xa1s antes de repasar los apuntes tomados en clase?')),
                ('pregunta7', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles dedicar tu tiempo libre entre las 4:00 de la tarde y a las 9:00 de la noche a otras actividades que no sean estudiar?')),
                ('pregunta8', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfDescubres algunas veces de pronto,que debes entregar una tarea antes de lo que cre\xc3\xadas?')),
                ('pregunta9', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfte retrasas, con frecuencia en una asignatura debido a que tienes que estudiar otra?')),
                ('pregunta10', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe patrece que tu rendimiento es muy bajo en relaci\xc3\xb3n con el tiempo que dedicas al estudio')),
                ('pregunta11', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfEst\xc3\xa1 situado tu escritorio directamente frente a una ventana, puerta u otra fuente de distracci\xc3\xb3n?')),
                ('pregunta12', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles tener fotograf\xc3\xadas, trofeos o recuerdos sobre tu mesa de escritorio?')),
                ('pregunta13', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles estudiar recostado en tu cama o arellanado con un asiento comodo?')),
                ('pregunta14', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfProduce resplandor la l\xc3\xa1mpara que utilizas al estudiar?')),
                ('pregunta15', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Tu mesa de estudio \xc2\xbfest\xc3\xa1 tan desordenada y llena de objetos que no dispones de sitio suficiente para estudiar con eficacia?')),
                ('pregunta16', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles interrumpir tu estudio por presonas que vienen a visitarte?')),
                ('pregunta17', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfEstudias, con frecuencia miestras tienes puesta la televisi\xc3\xb3n y/o la radio?')),
                ('pregunta18', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'En el lugar donde estudias, \xc2\xbfse pueden ver con facilidad revistas, fotos de j\xc3\xb3venes o materiales pertenecientes a tu afici\xc3\xb3n?')),
                ('pregunta19', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfCon frecuencia, interrumpen tu estudio actividades y ruidos que intervienen del exterior?')),
                ('pregunta20', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSuele hacerse lento tu estudio debido a que no tienes a la mano los libros y los materiales necesarios?')),
                ('diagnostico', models.CharField(blank=True, choices=[('0', 'Muy bajo'), ('1', 'bajo'), ('2', 'Por debajo del promedio'), ('3', 'Promedio bajo'), ('4', 'Promedio'), ('5', 'Promedio alto'), ('6', 'Por encima del promedio'), ('7', 'alto'), ('8', 'muy alto')], max_length=2)),
                ('comentarios', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TecnicasEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pregunta1', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTiendes a comenzar la lectura de un libro de texto sin hojear previamente los subtitulos y las instrucciones?')),
                ('pregunta2', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe saltas por lo general las figuras, graficas y tablas cuando estudias un tema?')),
                ('pregunta3', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSuele serte dificil seleccionar los puntoos de los temas de estudio?')),
                ('pregunta4', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe sorprendes con una cierta frecuencia, pensando en algo que no tiene nada que ver con lo que estudias?')),
                ('pregunta5', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles tener dificultad en entender tus apuntes de clases cuando tratas de repasarlos, despues de cierto tiempo?')),
                ('pregunta6', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Al tomar notas,\xc2\xbfte sueles quedar atras con frecuencia debido a que no puedes escribir con suficiente rapidez?')),
                ('pregunta7', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b"Poco despue de comenzar un curso,\xc2\xbfSueles encontrarte con tus apuntes formando un 'revoltijo' ?")),
                ('pregunta8', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTomas normalmente tus apuntes tratando de scribir las palabras exactas del docente?')),
                ('pregunta9', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Cuando tomas notas de un libro,\xc2\xbfTienes la costumbre de copiar el material necesario, palabra por palabra?')),
                ('pregunta10', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe es dificil preparar un temario apropiado para una evaluaci\xc3\xb3n?')),
                ('pregunta11', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTienes problemas para organizar los datos o el contenido de una evaluaci\xc3\xb3n?')),
                ('pregunta12', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfAl repasar el temario de una evaluaci\xc3\xb3n formulas un resumen de este?')),
                ('pregunta13', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe preparas aveces para una evaluaci\xc3\xb3n memorizando f\xc3\xb3rmulas, definiciones o reglas que no entiendes con claridad?')),
                ('pregunta14', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe resulta dif\xc3\xadcil decidir qu\xc3\xa9 estudiar y como estudiarlo cuando pre?')),
                ('pregunta15', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles tener dificultades para organizar, un orden l\xc3\xb3gico, las asignaturas que debes estudiar por temas?')),
                ('pregunta16', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Al preparar evaluaci\xc3\xb3n,\xc2\xbfSueles estudiar toda la asignatura, en el ultimo momento?')),
                ('pregunta17', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles entregar tus ex\xc3\xa1menes sin revisarlos detenidamente para ver si tienen alg\xc3\xban error cometido por descuido?')),
                ('pregunta18', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe es posible con frecuencia terminar una evaluaci\xc3\xb3n de exposici\xc3\xb3n de un tema en el tiempo prescrito?')),
                ('pregunta19', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b"\xc2\xbfSueles perder puntos en ex\xc3\xa1menes con preguntas de 'Verdadero-Falso',debido a que no lees detenidamente?")),
                ('pregunta20', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfEmpleas normalmente mucho tiempo en contestar la primera mitad de la prueva y tienes que apresurarte en la segunda?')),
                ('diagnostico', models.CharField(blank=True, choices=[('0', 'Muy bajo'), ('1', 'bajo'), ('2', 'Por debajo del promedio'), ('3', 'Promedio bajo'), ('4', 'Promedio'), ('5', 'Promedio alto'), ('6', 'Por encima del promedio'), ('7', 'alto'), ('8', 'muy alto')], max_length=2)),
                ('comentarios', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
