# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo11', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta1',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='', max_length=2, verbose_name='preguntas'),
        ),
    ]
