# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo11', '0002_auto_20160413_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta1',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta10',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta11',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta12',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta13',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta14',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta15',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta16',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta17',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta18',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta19',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta2',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta20',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta3',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta4',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta5',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta6',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta7',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta8',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta9',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name='preguntas'),
        ),
    ]
