# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 14:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anexo11', '0002_inventarioestudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioestudio',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='motivacionestudio',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
