# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anexo11', '0003_auto_20160418_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacionestudio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 20, 16, 8, 11, 937451, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacionestudio',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 20, 16, 8, 30, 432930, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
