# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo11', '0003_auto_20160706_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioestudio',
            name='pregunta1',
            field=models.CharField(choices=[('1', 'Nunca'), ('2', 'Raramente'), ('3', 'Ocacionalmente'), ('4', 'Usualmente'), ('5', 'Siempre')], max_length=2, verbose_name=b'Me ayuda a trazar o escribir a mano las palabras cuando tengo que aprenderlas de Memoria'),
        ),
        migrations.AlterField(
            model_name='inventarioestudio',
            name='pregunta14',
            field=models.CharField(choices=[('1', 'Nunca'), ('2', 'Raramente'), ('3', 'Ocacionalmente'), ('4', 'Usualmente'), ('5', 'Siempre')], max_length=2, verbose_name=b'Necesito copiar los ejemplos de la pizarra del maestro para examinarlos m\xc3\xa1s tarde'),
        ),
        migrations.AlterField(
            model_name='inventarioestudio',
            name='pregunta5',
            field=models.CharField(choices=[('1', 'Nunca'), ('2', 'Raramente'), ('3', 'Ocacionalmente'), ('4', 'Usualmente'), ('5', 'Siempre')], max_length=2, verbose_name=b'Al prestar atenci\xc3\xb3n a una conferencia, puedo recordar las ideas principales sin anotarlas'),
        ),
        migrations.AlterField(
            model_name='motivacionestudio',
            name='pregunta1',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Despu\xc3\xa9s de los primeros d\xc3\xadas o semanas del curso \xc2\xbfTiendes a perder inter\xc3\xa9s por el estudio?'),
        ),
        migrations.AlterField(
            model_name='motivacionestudio',
            name='pregunta11',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles dedicarte de modo casual, seg\xc3\xban el estado de \xc3\xa1nimo en que te encuentres?'),
        ),
        migrations.AlterField(
            model_name='motivacionestudio',
            name='pregunta14',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles pensar que los examenes son pruebas penosas que no se puede escapar y respecto a las cuales lo que se debe hacerse es sobrevivir, del modo que sea?'),
        ),
        migrations.AlterField(
            model_name='motivacionestudio',
            name='pregunta16',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTienes normalmente la sensaci\xc3\xb3n que los docentes exigen demasiadas horas de estudio fuera de clases?'),
        ),
        migrations.AlterField(
            model_name='motivacionestudio',
            name='pregunta19',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe sientes reacio, por lo general, a hablar con tus docentes de tus proyectos futuros , de estudio o profesionales?'),
        ),
        migrations.AlterField(
            model_name='motivacionestudio',
            name='pregunta2',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b"\xc2\xbfCrees que en general, basta estudiar lo necesario para obtener un 'aprobado' en las asignaturas?"),
        ),
        migrations.AlterField(
            model_name='motivacionestudio',
            name='pregunta5',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfCrees que es m\xc3\xa1s importante divertirte y disfrutar de la vida, que estudiar?'),
        ),
        migrations.AlterField(
            model_name='motivacionestudio',
            name='pregunta7',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe sientes habitualmente incapaz de concentrarte en tus estudios debido a que estas inquieto, aburrido o de mal humor ?'),
        ),
        migrations.AlterField(
            model_name='motivacionestudio',
            name='pregunta8',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfPiensas con frecuencia que las asignaturas que estudias tienen poco valor practico para ti?'),
        ),
        migrations.AlterField(
            model_name='motivacionestudio',
            name='pregunta9',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSientes, frecuentes deseos de abandonar la escuela y conseguir un trabajo?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta10',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe parece que tu rendimiento es muy bajo en relaci\xc3\xb3n con el tiempo que dedicas al estudio'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta15',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Tu mesa de estudio \xc2\xbfEst\xc3\xa1 tan desordenada y llena de objetos que no dispones de sitio suficiente para estudiar con eficacia?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta16',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles interrumpir tu estudio por personas que vienen a visitarte?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta18',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'En el lugar donde estudias, \xc2\xbfSe pueden ver con facilidad revistas, fotos de j\xc3\xb3venes o materiales pertenecientes a tu afici\xc3\xb3n?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta2',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfCrees que el sue\xc3\xb1o o el cansancio te impida estudiar eficazmente en muchas ocasiones?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta4',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTiendes a emplear tiempo en leer revistas, ver televisi\xc3\xb3n o charlar cu\xc3\xa1ndo debieras dedicarlo a estudiar?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta5',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Tus actividades sociales o deportivas \xc2\xbfTe llevan a menudo a descuidar tus tareas escolares?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta9',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe retrasas, con frecuencia en una asignatura debido a que tienes que estudiar otra?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta1',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTiendes a comenzar la lectura de un libro de texto sin hojear previamente los subt\xc3\xadtulos y las instrucciones?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta10',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe es dif\xc3\xadcil preparar un temario apropiado para una evaluaci\xc3\xb3n?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta14',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe resulta dif\xc3\xadcil decidir qu\xc3\xa9 estudiar y como estudiarlo cuando preparas una evaluaci\xc3\xb3n?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta15',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles tener dificultades para organizar, en un orden l\xc3\xb3gico, las asignaturas que debes estudiar por temas?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta16',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Al preparar evaluaci\xc3\xb3n,\xc2\xbfSueles estudiar toda la asignatura, en el \xc3\xbaltimo momento?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta17',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles entregar tus ex\xc3\xa1menes sin revisarlos detenidamente, para ver si tienen alg\xc3\xban error cometido por descuido?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta18',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe es posible con frecuencia terminar una evaluaci\xc3\xb3n de exposici\xc3\xb3n de un tema en el tiempo preescrito?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta2',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe saltas por lo general las figuras, gr\xc3\xa1ficas y tablas cu\xc3\xa1ndo estudias un tema?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta20',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfEmpleas normalmente mucho tiempo en contestar la primera mitad de la prueba y tienes que apresurarte en la segunda?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta3',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSuele serte dif\xc3\xadcil seleccionar los puntos de los temas de estudio?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta5',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles tener dificultad en entender tus apuntes de clases cu\xc3\xa1ndo tratas de repasarlos, despu\xc3\xa9s de cierto tiempo?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta6',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Al tomar notas,\xc2\xbfTe sueles quedar atr\xc3\xa1s con frecuencia debido a que no puedes escribir con suficiente rapidez?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta7',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b"Poco despu\xc3\xa9s de comenzar un curso \xc2\xbfSueles encontrarte con tus apuntes formando un 'revoltijo'?"),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta8',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTomas normalmente tus apuntes tratando de escribir las palabras exactas del docente?'),
        ),
        migrations.AlterField(
            model_name='tecnicasestudio',
            name='pregunta9',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Cuando tomas notas de un libro \xc2\xbfTienes la costumbre de copiar el material necesario, palabra por palabra?'),
        ),
    ]
