# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo11', '0004_auto_20160727_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioestudio',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='inventarioestudio',
            name='diagnostico_Auditivo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='inventarioestudio',
            name='diagnostico_Kinestesico',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='inventarioestudio',
            name='diagnostico_Visual',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
