# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexo11', '0005_auto_20160425_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta1',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles dejar para el ultimo la preparaci\xc3\xb3n de tus trabajos?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta10',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTe patrece que tu rendimiento es muy bajo en relaci\xc3\xb3n con el tiempo que dedicas al estudio'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta11',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfEst\xc3\xa1 situado tu escritorio directamente frente a una ventana, puerta u otra fuente de distracci\xc3\xb3n?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta12',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles tener fotograf\xc3\xadas, trofeos o recuerdos sobre tu mesa de escritorio?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta13',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles estudiar recostado en tu cama o arellanado con un asiento comodo?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta14',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfProduce resplandor la l\xc3\xa1mpara que utilizas al estudiar?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta15',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Tu mesa de estudio \xc2\xbfest\xc3\xa1 tan desordenada y llena de objetos que no dispones de sitio suficiente para estudiar con eficacia?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta16',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles interrumpir tu estudio por presonas que vienen a visitarte?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta17',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfEstudias, con frecuencia miestras tienes puesta la televisi\xc3\xb3n y/o la radio?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta18',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'En el lugar donde estudias, \xc2\xbfse pueden ver con facilidad revistas, fotos de j\xc3\xb3venes o materiales pertenecientes a tu afici\xc3\xb3n?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta19',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfCon frecuencia, interrumpen tu estudio actividades y ruidos que intervienen del exterior?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta2',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfCrees que el sue\xc3\xb1o o el cansancio te impida estudiar eficazmente en muchas ocasiones ?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta20',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSuele hacerse lento tu estudio debido a que no tienes a la mano los libros y los materiales necesarios?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta3',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfEs frecuente que no termines tu tarea a tiempo?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta4',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfTiendes a emplear tiempo en leer revistas, ver televisi\xc3\xb3n o charlar cuando debieras dedicarlo a estudiar?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta5',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'Tus actividades sociales o deportivas.\xc2\xbfTe llevan a menudo a descuidar tus tareas escolares?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta6',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles dejar pasar un d\xc3\xada o m\xc3\xa1s antes de repasar los apuntes tomados en clase?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta7',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfSueles dedicar tu tiempo libre entre las 4:00 de la tarde y a las 9:00 de la noche a otras actividades que no sean estudiar?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta8',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfDescubres algunas veces de pronto,que debes entregar una tarea antes de lo que cre\xc3\xadas?'),
        ),
        migrations.AlterField(
            model_name='organizacionestudio',
            name='pregunta9',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=2, verbose_name=b'\xc2\xbfte retrasas, con frecuencia en una asignatura debido a que tienes que estudiar otra?'),
        ),
    ]
