# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 16:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anexo11', '0007_motivacionestudio_tecnicasestudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivacionestudio',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='organizacionestudio',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='tecnicasestudio',
            name='comentarios',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
