# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('imagen', models.ImageField(blank=True, upload_to=b'')),
                ('des_imagen', models.CharField(blank=True, max_length=50)),
                ('num_formularios', models.IntegerField()),
            ],
        ),
    ]
